'''title'''
__title__ = 'musicdl'
'''description'''
__description__ = 'Musicdl: A lightweight music downloader written in pure python'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/musicdl'
'''version'''
__version__ = '2.9.0'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'PolyForm-Noncommercial-1.0.0'
'''copyright'''
__copyright__ = 'Copyright 2018-2030 Zhenchao Jin'