'''initialize'''
from .mitu import MituMusicClient
from .kkws import KKWSMusicClient
from .htqyy import HTQYYMusicClient
from .mgmp3 import MGMP3MusicClient
from .sgogo import SgogoMusicClient
from .xmfwav import XMFWAVMusicClient
from .twot58 import TwoT58MusicClient
from .fangpi import FangpiMusicClient
from .buguyy import BuguyyMusicClient
from .liziyy import LiziYYMusicClient
from .xiageba import XiagebaMusicClient
from .itingwa import ITingWaMusicClient
from .gequbao import GequbaoMusicClient
from .gequhai import GequhaiMusicClient
from .livepoo import LivePOOMusicClient
from .yinyueku import YinyuekuMusicClient
from .fivesong import FiveSongMusicClient
from .yinyuedao import YinyuedaoMusicClient